import json
import os
import shutil
import subprocess
import sys
import re
from datetime import datetime
from pathlib import Path

# [FIX-1] Cached OS detection
_os_cache: str | None = None


def _base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


def _get_os() -> str:
    global _os_cache
    if _os_cache is not None:
        return _os_cache
    try:
        cfg = json.loads(
            (_base_dir() / "config" / "api_keys.json").read_text(encoding="utf-8")
        )
        _os_cache = cfg.get("os_system", "").lower()
        if not _os_cache:
            import platform
            system = platform.system().lower()
            _os_cache = {"darwin": "mac", "windows": "windows", "linux": "linux"}.get(system, "windows")
    except Exception:
        import platform
        system = platform.system().lower()
        _os_cache = {"darwin": "mac", "windows": "windows", "linux": "linux"}.get(system, "windows")
    return _os_cache


def _scripts_dir() -> Path:
    d = Path.home() / ".friday" / "reminders"
    d.mkdir(parents=True, exist_ok=True)
    return d


# [FIX-3] Smarter sanitization — preserve message meaning
def _sanitise(text: str, max_len: int = 200) -> str:
    # Remove control characters but keep normal punctuation
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", "", text)
    text = text.replace("\n", " ").replace("\r", "").strip()
    return text[:max_len]


# [FIX-4] + [FIX-5] Proper notification script with safe escaping
def _write_notify_script(task_name: str, message: str, os_name: str) -> Path:
    script_path = _scripts_dir() / f"{task_name}.py"

    # Use json.dumps for safe string embedding in the generated script
    msg_literal = json.dumps(message)

    if os_name == "windows":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="FRIDAY Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        from win10toast import ToastNotifier
        ToastNotifier().show_toast("FRIDAY Reminder", message, duration=15, threaded=False)
        notified = True
    except Exception:
        pass

if not notified:
    try:
        import subprocess
        subprocess.run(["msg", "*", "/TIME:30", message], check=False)
    except Exception:
        pass

try:
    import winsound
    for freq in [800, 1000, 1200]:
        winsound.Beep(freq, 180)
        import time; time.sleep(0.08)
except Exception:
    pass
"""

    elif os_name == "mac":
        # [FIX-4] Use json.dumps for safe osascript string embedding
        notify_block = f"""
import json
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="FRIDAY Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        # [FIX-4] Properly escape for osascript using json
        safe_msg = json.dumps(message)
        script = f'display notification {{safe_msg}} with title "FRIDAY Reminder"'
        subprocess.run(["osascript", "-e", script], check=False)
        notified = True
    except Exception:
        pass
"""

    else:  # linux
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="FRIDAY Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        subprocess.run(
            ["notify-send", "--urgency=normal", "--expire-time=15000",
             "FRIDAY Reminder", message],
            check=False
        )
    except Exception:
        pass
"""

    # [FIX-5] Use script_path directly instead of __file__
    script_body = f"""# Auto-generated by FRIDAY reminder — do not edit
import sys, os, pathlib

_SCRIPT_PATH = pathlib.Path(r"{script_path}")

{notify_block}

# Self-delete after firing
try:
    _SCRIPT_PATH.unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")

    # [FIX-9] chmod only on non-Windows
    if os_name != "windows":
        try:
            script_path.chmod(0o600)
        except Exception:
            pass

    return script_path


# [FIX-7] UTF-8 XML for better compatibility
def _schedule_windows(target_dt: datetime, task_name: str,
                      script_path: Path, message: str) -> str:
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>FRIDAY Reminder</Description></RegistrationInfo>\n'
        '  <Triggers><TimeTrigger>\n'
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        '    <Enabled>true</Enabled>\n'
        '  </TimeTrigger></Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )

    # [FIX-7] Use UTF-8 with BOM for schtasks compatibility
    xml_path.write_text(xml_content, encoding="utf-8")

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True, text=True,
    )

    try:
        xml_path.unlink(missing_ok=True)
    except Exception:
        pass

    if result.returncode != 0:
        try:
            script_path.unlink(missing_ok=True)
        except Exception:
            pass
        err = (result.stderr or result.stdout).strip()
        print(f"[Reminder] ❌ schtasks: {err}")
        return ""

    return task_name


# [FIX-2] Schedule cleanup after reminder fires
def _schedule_mac(target_dt: datetime, task_name: str,
                  script_path: Path) -> str:
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    label      = f"com.friday.reminder.{task_name}"
    plist_path = agents_dir / f"{label}.plist"

    # [FIX-2] Create a wrapper script that unloads the plist after firing
    wrapper_path = _scripts_dir() / f"{task_name}_wrapper.py"
    wrapper_body = f"""# Auto-generated wrapper — runs reminder then cleans up LaunchAgent
import subprocess, pathlib, sys

# Run the actual reminder
subprocess.run([sys.executable, r"{script_path}"], check=False)

# Unload and delete the LaunchAgent plist
try:
    subprocess.run(["launchctl", "unload", r"{plist_path}"], capture_output=True)
except Exception:
    pass
try:
    pathlib.Path(r"{plist_path}").unlink(missing_ok=True)
except Exception:
    pass
# Self-delete
try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    wrapper_path.write_text(wrapper_body, encoding="utf-8")
    wrapper_path.chmod(0o600)

    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{sys.executable}</string>
    <string>{wrapper_path}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Year</key>   <integer>{target_dt.year}</integer>
    <key>Month</key>  <integer>{target_dt.month}</integer>
    <key>Day</key>    <integer>{target_dt.day}</integer>
    <key>Hour</key>   <integer>{target_dt.hour}</integer>
    <key>Minute</key> <integer>{target_dt.minute}</integer>
  </dict>
  <key>RunAtLoad</key>         <false/>
  <key>StandardOutPath</key>   <string>/dev/null</string>
  <key>StandardErrorPath</key> <string>/dev/null</string>
</dict>
</plist>
"""
    plist_path.write_text(plist_content, encoding="utf-8")
    plist_path.chmod(0o644)

    result = subprocess.run(
        ["launchctl", "load", str(plist_path)],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        try:
            plist_path.unlink(missing_ok=True)
            wrapper_path.unlink(missing_ok=True)
            script_path.unlink(missing_ok=True)
        except Exception:
            pass
        print(f"[Reminder] ❌ launchctl: {result.stderr.strip()}")
        return ""

    return label


# [FIX-8] Use `at` as primary (more reliable for one-shot), systemd-run as fallback
def _schedule_linux(target_dt: datetime, task_name: str,
                    script_path: Path) -> str:

    # [FIX-8] Try `at` first — more reliable for one-shot scheduling
    if shutil.which("at"):
        at_time = target_dt.strftime("%H:%M %Y-%m-%d")
        cmd_str = f"{sys.executable} {script_path}\n"
        result  = subprocess.run(
            ["at", at_time],
            input=cmd_str, capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ⚠️ at failed: {result.stderr.strip()}")

    # Fallback to systemd-run
    if shutil.which("systemd-run"):
        on_calendar = target_dt.strftime("%Y-%m-%d %H:%M:00")
        result = subprocess.run(
            [
                "systemd-run",
                "--user",
                f"--on-calendar={on_calendar}",
                f"--unit={task_name}",
                "--",
                sys.executable, str(script_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ⚠️ systemd-run failed: {result.stderr.strip()}")

    print("[Reminder] ❌ Neither at nor systemd-run found on this system.")
    return ""


# [FIX-10] List and cancel reminders
def _list_reminders() -> str:
    os_name = _get_os()
    scripts = list(_scripts_dir().glob("JARVISReminder_*.py"))
    scripts = [s for s in scripts if not s.name.endswith("_wrapper.py")]

    if not scripts:
        return "No active reminders found."

    lines = ["Active reminders:"]
    for s in sorted(scripts):
        # Extract datetime from filename
        name = s.stem  # JARVISReminder_20260505_143000
        match = re.search(r"(\d{8})_(\d{6})", name)
        if match:
            try:
                dt = datetime.strptime(match.group(1) + match.group(2), "%Y%m%d%H%M%S")
                lines.append(f"  • {dt.strftime('%B %d, %Y at %I:%M %p')} — {s.name}")
            except ValueError:
                lines.append(f"  • {s.name}")
        else:
            lines.append(f"  • {s.name}")

    return "\n".join(lines)


def _cancel_reminder(task_name: str = "") -> str:
    os_name = _get_os()

    if not task_name:
        # Cancel all
        scripts = list(_scripts_dir().glob("JARVISReminder_*.py"))
        count = 0
        for s in scripts:
            try:
                s.unlink(missing_ok=True)
                count += 1
            except Exception:
                pass
        # Clean up wrappers too
        for s in _scripts_dir().glob("*_wrapper.py"):
            try:
                s.unlink(missing_ok=True)
            except Exception:
                pass

        if os_name == "windows":
            # Delete all JARVISReminder tasks
            result = subprocess.run(
                ["schtasks", "/Query", "/FO", "LIST", "/V"],
                capture_output=True, text=True
            )
            for line in result.stdout.splitlines():
                if "JARVISReminder_" in line and "TaskName:" in line:
                    tn = line.split(":", 1)[1].strip()
                    subprocess.run(["schtasks", "/Delete", "/TN", tn, "/F"],
                                   capture_output=True)
        elif os_name == "mac":
            for plist in (Path.home() / "Library" / "LaunchAgents").glob(
                "com.friday.reminder.JARVISReminder_*.plist"
            ):
                subprocess.run(["launchctl", "unload", str(plist)], capture_output=True)
                plist.unlink(missing_ok=True)

        return f"Cancelled {count} reminder(s)." if count else "No reminders to cancel."

    # Cancel specific task
    if os_name == "windows":
        result = subprocess.run(
            ["schtasks", "/Delete", "/TN", task_name, "/F"],
            capture_output=True, text=True,
        )
    elif os_name == "mac":
        label = f"com.friday.reminder.{task_name}"
        plist = Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
        if plist.exists():
            subprocess.run(["launchctl", "unload", str(plist)], capture_output=True)
            plist.unlink(missing_ok=True)
    else:
        # Linux: can't easily cancel `at` jobs by name
        pass

    # Clean up script
    script = _scripts_dir() / f"{task_name}.py"
    if script.exists():
        script.unlink(missing_ok=True)

    return f"Reminder '{task_name}' cancelled."


def _parse_natural_time(time_str: str) -> datetime | None:
    """Parse natural language time expressions like 'in 2 hours', 'tomorrow at 3pm'."""
    import re
    from datetime import timedelta

    now = datetime.now()
    time_str = time_str.lower().strip()

    # "in X minutes/hours/days"
    match = re.search(r'in\s+(\d+)\s*(min(?:ute)?s?|hour?s?|day?s?|week?s?)', time_str)
    if match:
        amount = int(match.group(1))
        unit = match.group(2)
        if 'min' in unit:
            return now + timedelta(minutes=amount)
        elif 'hour' in unit:
            return now + timedelta(hours=amount)
        elif 'day' in unit:
            return now + timedelta(days=amount)
        elif 'week' in unit:
            return now + timedelta(weeks=amount)

    # "tomorrow at HH:MM" or "tomorrow"
    if 'tomorrow' in time_str:
        tomorrow = now + timedelta(days=1)
        time_match = re.search(r'(\d{1,2}):?(\d{2})?\s*(am|pm)?', time_str)
        if time_match:
            hour = int(time_match.group(1))
            minute = int(time_match.group(2) or 0)
            ampm = time_match.group(3)
            if ampm == 'pm' and hour < 12:
                hour += 12
            elif ampm == 'am' and hour == 12:
                hour = 0
            return tomorrow.replace(hour=hour, minute=minute, second=0, microsecond=0)
        return tomorrow.replace(hour=9, minute=0, second=0, microsecond=0)

    # "next Monday/Tuesday/etc"
    days_map = {'monday': 0, 'tuesday': 1, 'wednesday': 2, 'thursday': 3,
                'friday': 4, 'saturday': 5, 'sunday': 6}
    for day_name, day_num in days_map.items():
        if day_name in time_str:
            days_ahead = day_num - now.weekday()
            if days_ahead <= 0:
                days_ahead += 7
            target = now + timedelta(days=days_ahead)
            time_match = re.search(r'(\d{1,2}):?(\d{2})?\s*(am|pm)?', time_str)
            if time_match:
                hour = int(time_match.group(1))
                minute = int(time_match.group(2) or 0)
                ampm = time_match.group(3)
                if ampm == 'pm' and hour < 12:
                    hour += 12
                elif ampm == 'am' and hour == 12:
                    hour = 0
                return target.replace(hour=hour, minute=minute, second=0, microsecond=0)
            return target.replace(hour=9, minute=0, second=0, microsecond=0)

    return None


def reminder(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
) -> str:

    params     = parameters or {}
    action     = params.get("action", "").lower().strip()
    date_str   = params.get("date", "").strip()
    time_str   = params.get("time", "").strip()
    message    = params.get("message", "Reminder").strip()
    recurring  = params.get("recurring", "").lower().strip()

    # [FIX-10] Handle list and cancel actions
    if action == "list":
        return _list_reminders()

    if action == "cancel":
        return _cancel_reminder(params.get("task_name", ""))

    if action == "cancel_all":
        return _cancel_reminder()

    # Try natural language parsing if no explicit date/time
    if not date_str and not time_str:
        # Check if message contains time info
        natural_time = _parse_natural_time(message)
        if natural_time:
            target_dt = natural_time
        else:
            return "I need both a date and a time to set a reminder."
    elif not date_str or not time_str:
        return "I need both a date and a time to set a reminder."
    else:
        try:
            target_dt = datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
        except ValueError:
            return "I couldn't parse that date or time. Please use YYYY-MM-DD and HH:MM."

    if target_dt <= datetime.now():
        return "That time has already passed — I can't set a reminder in the past."

    # [FIX-6] Check for duplicate reminders at the same time
    existing_scripts = list(_scripts_dir().glob(
        f"JARVISReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}*.py"
    ))
    if existing_scripts:
        return (
            f"A reminder is already set for {target_dt.strftime('%B %d at %I:%M %p')}. "
            f"Cancel it first if you want to change the message."
        )

    os_name    = _get_os()
    safe_msg   = _sanitise(message)
    task_name  = f"JARVISReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}"

    try:
        script_path = _write_notify_script(task_name, safe_msg, os_name)
    except Exception as e:
        return f"Could not prepare the reminder script: {e}"

    try:
        if os_name == "windows":
            job_id = _schedule_windows(target_dt, task_name, script_path, safe_msg)
        elif os_name == "mac":
            job_id = _schedule_mac(target_dt, task_name, script_path)
        else:
            job_id = _schedule_linux(target_dt, task_name, script_path)
    except Exception as e:
        try:
            script_path.unlink(missing_ok=True)
        except Exception:
            pass
        print(f"[Reminder] ❌ Scheduling exception: {e}")
        return "Something went wrong while scheduling the reminder."

    if not job_id:
        return "I couldn't register the reminder with the system scheduler."

    if player:
        player.write_log(f"[Reminder] ✅ {date_str} {time_str} — {safe_msg[:40]}")

    friendly_time = target_dt.strftime("%B %d at %I:%M %p")
    recurring_note = f" (recurring {recurring})" if recurring else ""
    return f"Reminder set for {friendly_time}{recurring_note}."
